name: mineEconomy
version: ${project.version}
main: pl.minecodes.mineeconomy.EconomyPlugin
api-version: 1.13
authors: [ _arturek ]
description: Economy for CampFire.pl
depend: [ Vault ]
website: https://minecodes.pl/