name: mineEconomy
version: ${project.version}
main: pl.arturekdev.mineEconomy.EconomyPlugin
api-version: 1.13
authors: [ _arturek ]
description: Economy for CampFire.pl
depend: [ mineDatabase, Vault ]
website: https://minecodes.pl/
commands:
  money: